site_name: Welcome to WL Japan Event Report Site
nav:
    - Home: index.md
    - Past Event:
        - "第1回": "past_event/01.md"
        - "第2回": "past_event/02.md"
        - "第3回": "past_event/03.md"
        - "第4回": "past_event/04.md"
        - "第5回": "past_event/05.md"
        - "第6回": "past_event/06.md"
        - "第7回": "past_event/07.md"
        - "第8回": "past_event/08.md"
        - "第9回": "past_event/09.md"
        - "第10回": "past_event/10.md"
        - "第11回": "past_event/11.md"
        - "第12回": "past_event/12.md"
        - "第13回": "past_event/13.md"
        - "第14回": "past_event/14.md"
        - "第15回": "past_event/15.md"
        - "第16回": "past_event/16.md"
        - "第17回": "past_event/17.md"
        - "第18回": "past_event/18.md"
        - "第19回": "past_event/19.md"
        - "第20回": "past_event/20.md"
        - "第21回": "past_event/21.md"
        - "第22回": "past_event/22.md"
        - "第23回": "past_event/23.md"
        - "第24回": "past_event/24.md"
        - "第25回": "past_event/25.md"
        - "第26回": "past_event/26.md"
        - "第27回": "past_event/27.md"
        - "第28回": "past_event/28.md"
        - "第29回": "past_event/29.md"
        - "第30回": "past_event/30.md"
        - "第31回": "past_event/31.md"
        - "第32回": "past_event/32.md"
        - "第32回": "past_event/33.md"
theme:
    name: material
extra:
    search:
        language: 'ja'
    font:
        text: "Noto Sans JP"
        code: "Consolas"
